import { automaticFormatArguments, canTransition, canonicalMediaUrl, capabilitiesFor, classifyErrorText, confidentMatch, createDownloadPolicy, detectSource, isUnavailableSource, mediaFilename, normalizeError, parseCapabilities, parseDownloadProgress, parseDownloadRequest, parseEngineStatus, parseReleaseInfo, parseResolvedMedia, sanitizeFilename, scoreCandidate, spotifyTrackId, supports } from '../../src/core';
describe('shared Savewave core', () => {
  it('detects supported sources and rejects non-http or lookalike domains', () => { expect(detectSource('https://youtu.be/abc')).toBe('youtube'); expect(detectSource('https://cdn.test/file.mp4')).toBe('direct'); expect(detectSource('file:///secret.mp4')).toBe('unknown'); expect(detectSource('https://evilinstagram.com/p/example')).toBe('unknown'); });
  it('uses the reliable watch endpoint for genuine YouTube Shorts only', () => { expect(canonicalMediaUrl('https://www.youtube.com/shorts/OfCy6QKf6jM?feature=share')).toBe('https://www.youtube.com/watch?v=OfCy6QKf6jM'); expect(canonicalMediaUrl('https://notyoutube.com/shorts/OfCy6QKf6jM')).toBe('https://notyoutube.com/shorts/OfCy6QKf6jM'); });
  it('reports honest web/native capabilities', () => { expect(supports(capabilitiesFor('web'), 'youtube', 'video')).toBe(false); expect(supports(capabilitiesFor('web'), 'direct', 'video')).toBe(true); expect(supports(capabilitiesFor('android'), 'spotify', 'audio')).toBe(true); for (const platform of ['web', 'desktop', 'android'] as const) for (const source of ['instagram', 'facebook', 'twitter'] as const) expect(supports(capabilitiesFor(platform), source, 'video')).toBe(false); });
  it('recognizes removed providers without treating their URLs as direct media', () => { for (const url of ['https://www.instagram.com/reel/example/', 'https://facebook.com/video.mp4', 'https://fb.watch/example', 'https://x.com/user/status/123', 'https://twitter.com/user/status/123']) expect(isUnavailableSource(detectSource(url))).toBe(true); expect(isUnavailableSource(detectSource('https://example.com/video.mp4'))).toBe(false); });
  it('keeps automatic formats simple', () => { expect(automaticFormatArguments('audio')).toContain('bestaudio/best'); expect(automaticFormatArguments('video')).toContain('bestvideo+bestaudio/best'); });
  it('owns retry, format, and bounded multi-item policy in the shared core', () => { expect(createDownloadPolicy('audio')).toMatchObject({ formatSelector: 'bestaudio/best', extractAudio: true, retries: 5, maxItems: 1 }); expect(createDownloadPolicy('video')).toMatchObject({ formatSelector: 'bestvideo+bestaudio/best', mergeOutputFormat: 'mp4/mkv', fragmentRetries: 5, maxItems: 1 }); for (const source of ['instagram', 'facebook', 'threads', 'twitter'] as const) { expect(createDownloadPolicy('video', source)).toMatchObject({ formatSelector: 'best', maxItems: 20 }); expect(automaticFormatArguments('video', source)).toEqual(['-f', 'best']); } });
  it('sanitizes shared filenames', () => { expect(mediaFilename('Artist', 'Song: Live?', 'm4a')).toBe('Artist - Song Live.m4a'); expect(sanitizeFilename('CON.mp4')).toBe('_CON.mp4'); });
  it('enforces state transitions', () => { expect(canTransition('resolved', 'downloading')).toBe(true); expect(canTransition('idle', 'completed')).toBe(false); });
  it('normalizes unknown errors without leaking details', () => { expect(normalizeError(new Error('raw internal trace')).message).toBe('Download failed.'); });
  it('normalizes Tauri string error codes', () => { expect(normalizeError('MATCH_CONFIDENCE_LOW').message).toBe('Could not confidently match this Spotify track.'); });
  it('accepts bounded download commands and rejects malformed bridge input', () => {
    expect(parseDownloadRequest({ url: 'https://example.com/video', mode: 'audio', title: 'Track', source: 'instagram' })).toMatchObject({ mode: 'audio', title: 'Track', source: 'instagram' });
    expect(() => parseDownloadRequest({ url: 'file:///private.txt', mode: 'audio' })).toThrow('Unsupported media link.');
    expect(() => parseDownloadRequest({ url: 'https://example.com', mode: 'archive' })).toThrow('Media processing failed.');
  });
  it('validates native progress bounds before rendering them', () => {
    expect(parseDownloadProgress({ jobId: 'job_1', state: 'downloading', percent: 42 }).percent).toBe(42);
    expect(() => parseDownloadProgress({ jobId: '../job', state: 'downloading', percent: 101 })).toThrow('Media processing failed.');
    expect(() => parseDownloadProgress({ jobId: 'job_1', state: 'mystery' })).toThrow('Media processing failed.');
    expect(parseDownloadProgress({ jobId: 'job_1', state: 'completed', filenames: ['one.jpg', 'two.mp4'] }).filenames).toHaveLength(2);
    expect(() => parseDownloadProgress({ jobId: 'job_1', state: 'completed', filenames: Array(21).fill('item.jpg') })).toThrow('Media processing failed.');
  });
  it('validates resolved media and bounded Spotify choices', () => {
    const base = { success: true, platform: 'youtube', title: 'Song', creator: 'Artist', type: 'audio', qualityLabel: 'Audio', sourceUrl: 'https://youtube.com/watch?v=abc' };
    expect(parseResolvedMedia(base).platform).toBe('youtube');
    expect(() => parseResolvedMedia({ ...base, platform: 'malicious' })).toThrow('Media processing failed.');
    expect(() => parseResolvedMedia({ ...base, selectionRequired: true, sourceUrl: '', matchOptions: [] })).toThrow('Media processing failed.');
    expect(parseResolvedMedia({ ...base, selectionRequired: false, matchOptions: [] }).matchOptions).toBeUndefined();
  });
  it('validates engine, capability, and release responses', () => {
    expect(parseEngineStatus({ available: true, version: '1.0.11', engineVersion: '2026.08.19' }).available).toBe(true);
    expect(() => parseEngineStatus({ available: 'yes', version: '1.0.11' })).toThrow('Media processing failed.');
    expect(parseCapabilities(capabilitiesFor('android')).platform).toBe('android');
    expect(() => parseCapabilities({ platform: 'android', sources: {} })).toThrow('Media processing failed.');
    expect(parseReleaseInfo({})).toBeNull();
    expect(() => parseReleaseInfo({ version: '2.0.0', updateAvailable: true, downloadUrl: 'javascript:alert(1)' })).toThrow();
  });
  it('classifies provider failures without exposing raw engine output', () => { expect(classifyErrorText('HTTP Error 429: Too Many Requests')).toBe('RATE_LIMITED'); expect(classifyErrorText('ERROR: ffmpeg merge failed at C:\\private\\file')).toBe('FFMPEG_FAILED'); expect(normalizeError('SOURCE_FORBIDDEN raw provider details').message).toBe('This source requires access Savewave does not have.'); });
  it('reports unsupported photo extraction instead of a generic download failure', () => { expect(classifyErrorText('[Instagram] id: No video formats found!')).toBe('POST_IMAGES_UNSUPPORTED'); expect(normalizeError('POST_IMAGES_UNSUPPORTED').message).toContain('photo post'); });
  it('does not mislabel YouTube extraction errors as photo posts', () => { expect(classifyErrorText('[youtube] id: No video formats found!')).toBe('NO_MEDIA_FOUND'); });
  it('does not treat private social media as a broken public download', () => { expect(classifyErrorText('This is a private post. Log in to view it')).toBe('SOURCE_FORBIDDEN'); });
  it('requires artist identity and rejects wrong versions', () => { const track = { title: 'Tum Hi Ho', primaryArtist: 'Arijit Singh', artists: ['Arijit Singh'], duration: 262 }; expect(scoreCandidate(track, { title: 'Tum Hi Ho', artist: 'Arijit Singh', duration: 262, official: true })).toBeGreaterThanOrEqual(80); expect(scoreCandidate(track, { title: 'Tum Hi Ho Remix', artist: 'Arijit Singh', duration: 262 })).toBeLessThan(80); });
  it('rejects ambiguous Spotify matches', () => { const track = { title: 'Song', primaryArtist: 'Artist', artists: ['Artist'], duration: 200 }; const candidate = { title: 'Song', artist: 'Artist', duration: 200 }; expect(confidentMatch(track, [candidate, { ...candidate }])).toBeNull(); });
  it('keys remembered Spotify choices by the non-personal track id only', () => { expect(spotifyTrackId('https://open.spotify.com/track/4cOdK2wGLETKBW3PvgPWqT?si=private')).toBe('4cOdK2wGLETKBW3PvgPWqT'); expect(spotifyTrackId('https://open.spotify.com/playlist/example')).toBeNull(); });
  it('accepts an exact artist Topic recording over a close official alternative', () => { const track = { title: 'RUN IT UP', primaryArtist: 'NEFFEX', artists: ['NEFFEX'], duration: 234 }; const topic = { title: 'RUN IT UP', uploader: 'NEFFEX - Topic', duration: 235 }; const alternate = { title: 'NEFFEX - RUN IT UP Copyright Free', uploader: 'NEFFEX', duration: 235 }; expect(confidentMatch(track, [topic, alternate])?.candidate).toBe(topic); });
  it('does not reward verified third-party lyric channels as official artists', () => { const track = { title: 'Man On The Moon', primaryArtist: 'Alan Walker', artists: ['Alan Walker', 'Benjamin Ingrosso'], duration: 179 }; const lyric = { title: 'Alan Walker x Benjamin Ingrosso - Man On The Moon Lyrics', uploader: '7clouds', duration: 177, official: true }; expect(scoreCandidate(track, lyric)).toBeLessThan(80); });
  it('accepts independently corroborated copies of the same recording', () => { const track = { title: 'Man On The Moon', primaryArtist: 'Alan Walker', artists: ['Alan Walker', 'Benjamin Ingrosso'], duration: 179 }; const first = { title: 'Alan Walker x Benjamin Ingrosso - Man On The Moon', uploader: 'Lost Songs', duration: 179 }; const second = { title: 'Alan Walker x Benjamin Ingrosso - Man On The Moon', uploader: 'KINQS Radio', duration: 179 }; expect(confidentMatch(track, [first, second])?.candidate).toBe(first); });
  it('corroborates the same recording when YouTube omits a composer credit', () => { const track = { title: 'O Saathi', primaryArtist: 'Atif Aslam', artists: ['Atif Aslam', 'Arko'], duration: 252 }; const first = { title: 'Atif Aslam - O Saathi', uploader: 'Music One', duration: 252 }; const second = { title: 'O Saathi - Atif Aslam', uploader: 'Music Two', duration: 253 }; expect(confidentMatch(track, [first, second])?.candidate).toBe(first); });
  it('rejects corroboration when the apparent recording is a modified version', () => { const track = { title: 'Man On The Moon', primaryArtist: 'Alan Walker', artists: ['Alan Walker', 'Benjamin Ingrosso'], duration: 179 }; const first = { title: 'Alan Walker x Benjamin Ingrosso - Man On The Moon 8D', uploader: 'One', duration: 179 }; const second = { title: 'Alan Walker x Benjamin Ingrosso - Man On The Moon 8D', uploader: 'Two', duration: 179 }; expect(confidentMatch(track, [first, second])).toBeNull(); });
  it('matches soundtrack catalogue titles to their base song title', () => { const track = { title: 'Hua Main (From "ANIMAL")', primaryArtist: 'Raghav Chaitanya', artists: ['Raghav Chaitanya', 'Pritam'], duration: 277 }; const topic = { title: 'Hua Main', uploader: 'Raghav Chaitanya - Topic', duration: 277 }; expect(confidentMatch(track, [topic])?.candidate).toBe(topic); });
  it('matches localized artist scripts when structured title and duration identify the recording', () => { const track = { title: 'OverThink - 动画《时光代理人》片尾曲', primaryArtist: '饭卡', artists: ['饭卡'], duration: 181 }; const officialSong = { videoId: '1wdxBfUcun8', resultType: 'song' as const, title: 'OverThink(動畫《時光代理人》片尾曲)', artists: ['飯卡'], duration: 181 }; expect(confidentMatch(track, [officialSong])?.candidate).toBe(officialSong); });
  it('does not recover localized artist spelling without matching recording duration', () => { const track = { title: 'OverThink - 动画《时光代理人》片尾曲', primaryArtist: '饭卡', artists: ['饭卡'], duration: 181 }; const wrongRecording = { videoId: 'wrong', resultType: 'song' as const, title: 'OverThink(動畫《時光代理人》片尾曲)', artists: ['飯卡'], duration: 214 }; expect(confidentMatch(track, [wrongRecording])).toBeNull(); });
  it('matches localized featured-artist credits and bilingual catalog titles', () => { const track = { title: 'ピュア (feat. 橋本絵莉子)', primaryArtist: 'PAS TASTA', artists: ['PAS TASTA', 'Eriko Hashimoto'], duration: 201 }; const officialSong = { videoId: 'tI9T0uGx4kI', resultType: 'song' as const, title: 'ピュア - Pure (feat. Eriko Hashimoto)', artists: ['PAS TASTA'], duration: 201 }; expect(confidentMatch(track, [officialSong])?.candidate).toBe(officialSong); });
  it('still rejects a remixed localized-feature candidate', () => { const track = { title: 'ピュア (feat. 橋本絵莉子)', primaryArtist: 'PAS TASTA', artists: ['PAS TASTA', 'Eriko Hashimoto'], duration: 201 }; const remix = { videoId: 'remix', resultType: 'song' as const, title: 'ピュア - Pure [tofubeats Remix] (feat. Eriko Hashimoto)', artists: ['PAS TASTA'], duration: 201 }; expect(confidentMatch(track, [remix])).toBeNull(); });
});
