import { automaticFormatArguments, canTransition, capabilitiesFor, confidentMatch, detectSource, mediaFilename, normalizeError, sanitizeFilename, scoreCandidate, supports } from '../../src/core';
describe('shared Savewave core', () => {
  it('detects supported sources and rejects non-http or lookalike domains', () => { expect(detectSource('https://youtu.be/abc')).toBe('youtube'); expect(detectSource('https://cdn.test/file.mp4')).toBe('direct'); expect(detectSource('file:///secret.mp4')).toBe('unknown'); expect(detectSource('https://evilinstagram.com/p/example')).toBe('unknown'); });
  it('reports honest web/native capabilities', () => { expect(supports(capabilitiesFor('web'), 'youtube', 'video')).toBe(false); expect(supports(capabilitiesFor('web'), 'direct', 'video')).toBe(true); expect(supports(capabilitiesFor('android'), 'spotify', 'audio')).toBe(true); });
  it('keeps automatic formats simple', () => { expect(automaticFormatArguments('audio')).toContain('bestaudio/best'); expect(automaticFormatArguments('video')).toContain('bestvideo*+bestaudio/best'); });
  it('sanitizes shared filenames', () => { expect(mediaFilename('Artist', 'Song: Live?', 'm4a')).toBe('Artist - Song Live.m4a'); expect(sanitizeFilename('CON.mp4')).toBe('_CON.mp4'); });
  it('enforces state transitions', () => { expect(canTransition('resolved', 'downloading')).toBe(true); expect(canTransition('idle', 'completed')).toBe(false); });
  it('normalizes unknown errors without leaking details', () => { expect(normalizeError(new Error('raw internal trace')).message).toBe('Download failed.'); });
  it('normalizes Tauri string error codes', () => { expect(normalizeError('MATCH_CONFIDENCE_LOW').message).toBe('Could not confidently match this Spotify track.'); });
  it('requires artist identity and rejects wrong versions', () => { const track = { title: 'Tum Hi Ho', primaryArtist: 'Arijit Singh', artists: ['Arijit Singh'], duration: 262 }; expect(scoreCandidate(track, { title: 'Tum Hi Ho', artist: 'Arijit Singh', duration: 262, official: true })).toBeGreaterThanOrEqual(80); expect(scoreCandidate(track, { title: 'Tum Hi Ho Remix', artist: 'Arijit Singh', duration: 262 })).toBeLessThan(80); });
  it('rejects ambiguous Spotify matches', () => { const track = { title: 'Song', primaryArtist: 'Artist', artists: ['Artist'], duration: 200 }; const candidate = { title: 'Song', artist: 'Artist', duration: 200 }; expect(confidentMatch(track, [candidate, { ...candidate }])).toBeNull(); });
  it('accepts an exact artist Topic recording over a close official alternative', () => { const track = { title: 'RUN IT UP', primaryArtist: 'NEFFEX', artists: ['NEFFEX'], duration: 234 }; const topic = { title: 'RUN IT UP', uploader: 'NEFFEX - Topic', duration: 235 }; const alternate = { title: 'NEFFEX - RUN IT UP Copyright Free', uploader: 'NEFFEX', duration: 235 }; expect(confidentMatch(track, [topic, alternate])?.candidate).toBe(topic); });
  it('does not reward verified third-party lyric channels as official artists', () => { const track = { title: 'Man On The Moon', primaryArtist: 'Alan Walker', artists: ['Alan Walker', 'Benjamin Ingrosso'], duration: 179 }; const lyric = { title: 'Alan Walker x Benjamin Ingrosso - Man On The Moon Lyrics', uploader: '7clouds', duration: 177, official: true }; expect(scoreCandidate(track, lyric)).toBeLessThan(80); });
  it('accepts independently corroborated copies of the same recording', () => { const track = { title: 'Man On The Moon', primaryArtist: 'Alan Walker', artists: ['Alan Walker', 'Benjamin Ingrosso'], duration: 179 }; const first = { title: 'Alan Walker x Benjamin Ingrosso - Man On The Moon', uploader: 'Lost Songs', duration: 179 }; const second = { title: 'Alan Walker x Benjamin Ingrosso - Man On The Moon', uploader: 'KINQS Radio', duration: 179 }; expect(confidentMatch(track, [first, second])?.candidate).toBe(first); });
  it('corroborates the same recording when YouTube omits a composer credit', () => { const track = { title: 'O Saathi', primaryArtist: 'Atif Aslam', artists: ['Atif Aslam', 'Arko'], duration: 252 }; const first = { title: 'Atif Aslam - O Saathi', uploader: 'Music One', duration: 252 }; const second = { title: 'O Saathi - Atif Aslam', uploader: 'Music Two', duration: 253 }; expect(confidentMatch(track, [first, second])?.candidate).toBe(first); });
  it('rejects corroboration when the apparent recording is a modified version', () => { const track = { title: 'Man On The Moon', primaryArtist: 'Alan Walker', artists: ['Alan Walker', 'Benjamin Ingrosso'], duration: 179 }; const first = { title: 'Alan Walker x Benjamin Ingrosso - Man On The Moon 8D', uploader: 'One', duration: 179 }; const second = { title: 'Alan Walker x Benjamin Ingrosso - Man On The Moon 8D', uploader: 'Two', duration: 179 }; expect(confidentMatch(track, [first, second])).toBeNull(); });
  it('matches soundtrack catalogue titles to their base song title', () => { const track = { title: 'Hua Main (From "ANIMAL")', primaryArtist: 'Raghav Chaitanya', artists: ['Raghav Chaitanya', 'Pritam'], duration: 277 }; const topic = { title: 'Hua Main', uploader: 'Raghav Chaitanya - Topic', duration: 277 }; expect(confidentMatch(track, [topic])?.candidate).toBe(topic); });
});
